#ifndef STRINGCONVERTER_CPP_I
#define STRINGCONVERTER_CPP_I
#include <unordered_map>
#include <vector>
#include <fstream>
#include <string>
#include <msclr\marshal_cppstd.h>

class PkmStringConverter{
private:
    static std::unordered_map<char, char> CHARACTER_TABLE;
    static std::unordered_map<char, std::string> ITEM_NAME_TABLE;
    static std::string badgeNames[8];
    static std::vector<std::string> pokemonNames;
    static std::vector<std::string> pokemonNamesById;
public:
    static std::string getBadgeName(char i){ return badgeNames[i]; }
    
    static std::string getPokemonName(char i){ return pokemonNames[(unsigned char)i]; }
    static std::string getPokemonName(unsigned char i){ return pokemonNames[i]; }

    static std::string getPokemonNameById(char i){return pokemonNamesById[(unsigned char)i]; }
    static std::string getPokemonNameById(unsigned char i){return pokemonNamesById[i]; }
    
    // TODO make a system to std string
    static std::string toStdString(System::String^ str) {
        msclr::interop::marshal_context ctx;
        return ctx.marshal_as<std::string>(str);
    }

    static System::String^ toSystemString(std::string str) {
        msclr::interop::marshal_context ctx;
        return ctx.marshal_as<System::String^>(str);
    }

    static std::string getTextSpeedStr(char textSpeed){
        switch(textSpeed){
            case 0b001:
                return "Fast";
            case 0b011:
                return "Normal";
            case 0b101:
                return "Slow";
            default:
                return "Invalid: " + std::to_string(textSpeed);
        }
    }

    static std::string decodeString(int len, char initial[]){
        std::string res = "";
        for(int i = 0; i < len; i++){
            res += CHARACTER_TABLE[initial[i]];
        }
        return res;
    }

    static std::string decodeString(std::string val){
        std::string res = "";
        for(unsigned char i = 0; i < val.length(); i++){
            res += decodeChar(val[i]);
        }
        return res;
    }

    static char decodeChar(char index){
        if(CHARACTER_TABLE.find(index) != CHARACTER_TABLE.end()){
            return CHARACTER_TABLE.at(index);
        }
        return (char)0;
    }

    static std::string getItemName(char index){
        if(ITEM_NAME_TABLE.find(index) != ITEM_NAME_TABLE.end()){
            return ITEM_NAME_TABLE.at(index);
        }
        return "Invalid Item! (Index " + std::to_string((unsigned short) index) + ")";
    }
};

// Badge Names
std::string PkmStringConverter::badgeNames[8] = {"Boulder", "Cascade", "Thunder", "Rainbow", "Soul", "Marsh", "Volcano", "Earth"};

// Pokemon Names by internal ID instead of by pokedex
std::vector<std::string> PkmStringConverter::pokemonNamesById = {
    "'M",
    "Rhydon",
    "Kangaskhan",
    "Nidoran♂",
    "Clefairy",
    "Spearow",
    "Voltorb",
    "Nidoking",
    "Slowbro",
    "Ivysaur",
    "Exeggutor",
    "Lickitung",
    "Exeggcute",
    "Grimer",
    "Gengar",
    "Nidoran♀",
    "Nidoqueen",
    "Cubone",
    "Rhyhorn",
    "Lapras",
    "Arcanine",
    "Mew",
    "Gyarados",
    "Shellder",
    "Tentacool",
    "Gastly",
    "Scyther",
    "Staryu",
    "Blastoise",
    "Pinsir",
    "Tangela",
    "Missingno: 0x1F",
    "Missingno: 0x20",
    "Growlithe",
    "Onix",
    "Fearow",
    "Pidgey",
    "Slowpoke",
    "Kadabra",
    "Graveler",
    "Chansey",
    "Machoke",
    "Mr. Mime",
    "Hitmonlee",
    "Hitmonchan",
    "Arbok",
    "Parasect",
    "Psyduck",
    "Drowzee",
    "Golem",
    "Missingno: 0x32",
    "Magmar",
    "Missingno: 0x34",
    "Electabuzz",
    "Magneton",
    "Koffing",
    "Missingno: 0x38",
    "Mankey",
    "Seel",
    "Diglett",
    "Tauros",
    "Missingno: 0x3D",
    "Missingno: 0x3E",
    "Missingno: 0x3F",
    "Farfetch'd",
    "Venonat",
    "Dragonite",
    "Missingno: 0x43",
    "Missingno: 0x44",
    "Missingno: 0x45",
    "Doduo",
    "Poliwag",
    "Jynx",
    "Moltres",
    "Articuno",
    "Zapdos",
    "Ditto",
    "Meowth",
    "Krabby",
    "Missingno: 0x4F",
    "Missingno: 0x50",
    "Missingno: 0x51",
    "Vulpix",
    "Ninetales",
    "Pikachu",
    "Raichu",
    "Missingno: 0x56",
    "Missingno: 0x57",
    "Dratini",
    "Dragonair",
    "Kabuto",
    "Kabutops",
    "Horsea",
    "Seadra",
    "Missingno: 0x5E",
    "Missingno: 0x5F",
    "Sandshrew",
    "Sandslash",
    "Omanyte",
    "Omastar",
    "Jigglypuff",
    "Wigglytuff",
    "Eevee",
    "Flareon",
    "Jolteon",
    "Vaporeon",
    "Machop",
    "Zubat",
    "Ekans",
    "Paras",
    "Poliwhirl",
    "Poliwrath",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Missingno: 0x73",
    "Dodrio",
    "Primeape",
    "Dugtrio",
    "Venomoth",
    "Dewgong",
    "Missingno: 0x79",
    "Missingno: 0x7A",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Machamp",
    "Missingno: 0x7F",
    "Golduck",
    "Hypno",
    "Golbat",
    "Mewtwo",
    "Snorlax",
    "Magikarp",
    "Missingno: 0x86",
    "Missingno: 0x87",
    "Muk",
    "Missingno: 0x89",
    "Kingler",
    "Cloyster",
    "Missingno: 0x8C",
    "Electrode",
    "Clefable",
    "Weezing",
    "Persian",
    "Marowak",
    "Missingno: 0x92",
    "Haunter",
    "Abra",
    "Alakazam",
    "Pidgeotto",
    "Pidgeot",
    "Starmie",
    "Bulbasaur",
    "Venusaur",
    "Tentacruel",
    "Missingno: 0x9C",
    "Goldeen",
    "Seaking",
    "Missingno: 0x9F",
    "Missingno: 0xA0",
    "Missingno: 0xA1",
    "Missingno: 0xA2",
    "Ponyta",
    "Rapidash",
    "Rattata",
    "Raticate",
    "Nidorino",
    "Nidorina",
    "Geodude",
    "Porygon",
    "Aerodactyl",
    "Missingno: 0xAC",
    "Magnemite",
    "Missingno: 0xAE",
    "Missingno: 0xAF",
    "Charmander",
    "Squirtle",
    "Charmeleon",
    "Wartortle",
    "Charizard",
    "Missingno: 0xB5",
    "Missingno: 0xB6",
    "Missingno: 0xB7",
    "Missingno: 0xB8",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Bellsprout",
    "Weepinbell",
    "Victreebell"
};

// Pokemon Names
std::vector<std::string> PkmStringConverter::pokemonNames = {
    "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "Nidoran♀",
        "Nidorina",
        "Nidoqueen",
        "Nidoran♂",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jiglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebell",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetch'd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "Mr. Mime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew"
};

// Character Mappings
std::unordered_map<char, char> PkmStringConverter::CHARACTER_TABLE = {
    {0x50, '\0'},
    {0x5D, '*'},
    {0x7F, ' '},
    {0x80, 'A'},
    {0x81, 'B'},
    {0x82, 'C'},
    {0x83, 'D'},
    {0x84, 'E'},
    {0x85, 'F'},
    {0x86, 'G'},
    {0x87, 'H'},
    {0x88, 'I'},
    {0x89, 'J'},
    {0x8A, 'K'},
    {0x8B, 'L'},
    {0x8C, 'M'},
    {0x8D, 'N'},
    {0x8E, 'O'},
    {0x8F, 'P'},
    {0x90, 'Q'},
    {0x91, 'R'},
    {0x92, 'S'},
    {0x93, 'T'},
    {0x94, 'U'},
    {0x95, 'V'},
    {0x96, 'W'},
    {0x97, 'X'},
    {0x98, 'Y'},
    {0x99, 'Z'},
    {0x9A, '('},
    {0x9B, ')'},
    {0x9C, ':'},
    {0x9D, ';'},
    {0x9E, '['},
    {0x9F, ']'},
    {0xA0, 'a'},
    {0xA1, 'b'},
    {0xA2, 'c'},
    {0xA3, 'd'},
    {0xA4, 'e'},
    {0xA5, 'f'},
    {0xA6, 'g'},
    {0xA7, 'h'},
    {0xA8, 'i'},
    {0xA9, 'j'},
    {0xAA, 'k'},
    {0xAB, 'l'},
    {0xAC, 'm'},
    {0xAD, 'n'},
    {0xAE, 'o'},
    {0xAF, 'p'},
    {0xB0, 'q'},
    {0xB1, 'r'},
    {0xB2, 's'},
    {0xB3, 't'},
    {0xB4, 'u'},
    {0xB5, 'v'},
    {0xB6, 'w'},
    {0xB7, 'x'},
    {0xB8, 'y'},
    {0xB9, 'z'},

    // unused characters
    {0xBA, 224},
    {0xBB, 232},
    {0xBC, 233},
    {0xBD, 249},
    {0xBE, 192},
    {0xBF, 193}, // Used in Spanish FALCÁN in-game trade, inaccessible from keyboard

    {0xC0, 195},
    {0xC1, 214},
    {0xC2, 220},
    {0xC3, 228},
    {0xC4, 246},
    {0xC5, 252},

    // unused characters
    {0xC6, "È"[0]},
    {0xC7, "É"[0]},
    {0xC8, "Ì"[0]},
    {0xC9, "Í"[0]}, // Used in Spanish MANÍA in-game trade, inaccessible from keyboard
    {0xCA, "Ñ"[0]},
    {0xCB, "Ò"[0]},
    {0xCC, "Ó"[0]},
    {0xCD, "Ù"[0]},
    {0xCE, "Ú"[0]},
    {0xCF, "á"[0]},
    {0xD0, "ì"[0]},
    {0xD1, "í"[0]},
    {0xD2, "ñ"[0]},
    {0xD3, "ò"[0]},
    {0xD4, "ó"[0]},
    {0xD5, "ú"[0]},

    {0xE0, "’"[0]},
    {0xE1, '{'}, /* Pk */
    {0xE2, '}'}, /* Mn */
    {0xE3, '-'},
    {0xE6, '?'},
    {0xE7, '!'},
    {0xE8, '.'}, // Alias decimal point to .
    {0xEF, "♂"[0]},
    {0xF1, "×"[0]},
    {0xF2, '.'},
    {0xF3, '/'},
    {0xF4, ','},
    {0xF5, "♀"[0]},
    {0xF6, '0'},
    {0xF7, '1'},
    {0xF8, '2'},
    {0xF9, '3'},
    {0xFA, '4'},
    {0xFB, '5'},
    {0xFC, '6'},
    {0xFD, '7'},
    {0xFE, '8'},
    {0xFF, '9'},
};


// Item Name Mappings
std::unordered_map<char, std::string> PkmStringConverter::ITEM_NAME_TABLE = {
    {0x1, "Master Ball"},
    {0x2, "Ultra Ball"},
    {0x3, "Great Ball"},
    {0x4, "Poke Ball"},
    {0x5, "Town Map"},
    {0x6, "Bicycle"},
    {0x7, "????? (Surfboard)"},
    {0x8, "Safari Ball"},
    {0x9, "Pokedex"},
    {0xA, "Moon Stone"},
    {0xB, "Antidote"},
    {0xC, "Burn Heal"},
    {0xD, "Ice Heal"},
    {0xE, "Awakening"},
    {0xF, "Paralyz Heal"},
    {0x10, "Full Restore"},
    {0x11, "Max Potion"},
    {0x12, "Hyper Potion"},
    {0x13, "Super Potion"},
    {0x14, "Potion"},
    {0x15, "Boulder Badge"},
    {0x16, "Cascade Badge"},
    {0x17, "ThunderBadge"},
    {0x18, "Rainbow Badge"},
    {0x19, "Soul Badge"},
    {0x1A, "Marsh Badge"},
    {0x1B, "Volcano Badge"},
    {0x1C, "Earth Badge"},
    {0x1D, "Escape Rope"},
    {0x1E, "Repel"},
    {0x1F, "Old Amber"},
    {0x20, "Fire Stone"},
    {0x21, "Thunderstone"},
    {0x22, "Water Stone"},
    {0x23, "HP Up"},
    {0x24, "Protein"},
    {0x25, "Iron"},
    {0x26, "Carbos"},
    {0x27, "Calcium"},
    {0x28, "Rare Candy"},
    {0x29, "Dome Fossil"},
    {0x2A, "Helix Fossil"},
    {0x2B, "Secret Key"},
    {0x2C, "?????"},
    {0x2D, "Bike Voucher"},
    {0x2E, "X Accuracy"},
    {0x2F, "Leaf Stone"},
    {0x30, "Card Key"},
    {0x31, "Nugget"},
    {0x32, "PP Up (glitched)"},
    {0x33, "Poke Doll"},
    {0x34, "Full Heal"},
    {0x35, "Revive"},
    {0x36, "Max Revive"},
    {0x37, "Guard Spec"},
    {0x38, "Super Repel"},
    {0x39, "Max Repel"},
    {0x3A, "Dire Hit"},
    {0x3B, "Coin"},
    {0x3C, "Fresh Water"},
    {0x3D, "Soda Pop"},
    {0x3E, "Lemonade"},
    {0x3F, "S.S. Ticket"},
    {0x40, "Gold Teeth"},
    {0x41, "X Attack"},
    {0x42, "X Defend"},
    {0x43, "X Speed"},
    {0x44, "X Special"},
    {0x45, "Coin Case"},
    {0x46, "Oak's Parcel"},
    {0x47, "Itemfinder"},
    {0x48, "Silph Scope"},
    {0x49, "Poke Flute"},
    {0x4A, "Lift Key"},
    {0x4B, "Exp. All"},
    {0x4C, "Old Rod"},
    {0x4D, "Good Rod"},
    {0x4E, "Super Rod"},
    {0x4F, "PP Up"},
    {0x50, "Ether"},
    {0x51, "Max Ether"},
    {0x52, "Elixer"},
    {0x53, "Max Elixer"},
    // HMs
    {0xC4, "HM01: Cut"},
    {0xC5, "HM02: Fly"},
    {0xC6, "HM03: Surf"},
    {0xC7, "HM04: Strength"},
    {0xC8, "HM05: Flash"},
    // TMs
    {0xC9, "TM01: Mega Punch"},
    {0xCA, "TM02: Razor Wind"},
    {0xCB, "TM03: Swords Dance"},
    {0xCC, "TM04: Whirlwind"},
    {0xCD, "TM05: Mega Kick"},
    {0xCE, "TM06: Toxic"},
    {0xCF, "TM07: Horn Drill"},
    {0xD0, "TM08: Body Slam"},
    {0xD1, "TM09: Take Down"},
    {0xD2, "TM10: Double-Edge"},
    {0xD3, "TM11: Bubble Beam"},
    {0xD4, "TM12: Water Gun"},
    {0xD5, "TM13: Ice Beam"},
    {0xD6, "TM14: Blizzard"},
    {0xD7, "TM15: Hyper Beam"},
    {0xD8, "TM16: Pay Day"},
    {0xD9, "TM17: Submission"},
    {0xDA, "TM18: Counter"},
    {0xDB, "TM19: Seismic Toss"},
    {0xDC, "TM20: Rage"},
    {0xDD, "TM21: Mega Drain"},
    {0xDE, "TM22: Solar Beam"},
    {0xDF, "TM23: Dragon Rage"},
    {0xE0, "TM24: Thunderbolt"},
    {0xE1, "TM25: Thunder"},
    {0xE2, "TM26: Earthquake"},
    {0xE3, "TM27: Fissure"},
    {0xE4, "TM28: Dig"},
    {0xE5, "TM29: Psychic"},
    {0xE6, "TM30: Teleport"},
    {0xE7, "TM31: Mimic"},
    {0xE8, "TM32: Double Team"},
    {0xE9, "TM33: Reflect"},
    {0xEA, "TM34: Bide"},
    {0xEB, "TM35: Metronome"},
    {0xEC, "TM36: Self-Destruct"},
    {0xED, "TM37: Egg Bomb"},
    {0xEE, "TM38: Fire Blast"},
    {0xEF, "TM39: Swift"},
    {0xF0, "TM40: Skull Bash"},
    {0xF1, "TM41: Soft-Boiled"},
    {0xF2, "TM42: Dream Eater"},
    {0xF3, "TM43: Sky Attack"},
    {0xF4, "TM44: Rest"},
    {0xF5, "TM45: Thunder Wave"},
    {0xF6, "TM46: Psywave"},
    {0xF7, "TM47: Explosion"},
    {0xF8, "TM48: Rock Slide"},
    {0xF9, "TM49: Tri Attack"},
    {0xFA, "TM50: Substitute"},
    {0xFB, "TM51: Cut (Glitch)"},
    {0xFC, "TM52: Fly (Glitch)"},
    {0xFD, "TM53: Surf (Glitch)"},
    {0xFE, "TM54: Strength (Glitch)"},
    {0xFF, "TM55: Flash (Glitch)"}
};

#endif